@echo off
echo Installing AI server requirements...
pip install -r requirements.txt
echo Starting FastAPI AI Inference Server on port 3002...
python -m uvicorn src.main:app --host 0.0.0.0 --port 3002
